---
abstract: 'Hacks for Plack and CGI under Apache2'
author:
  - 'Tim Retout <t.retout@cv-library.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Apache2CGIFix
requires:
  Plack::Middleware: 0
  parent: 0
version: 0.002
